// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {types} from '../models';

export function CopyFile(arg1:string,arg2:string):Promise<number>;

export function CreateDir(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DomReady(arg1:context.Context):Promise<void>;

export function FuzzyFindFiles(arg1:string,arg2:string):Promise<Array<types.FileStruct>>;

export function GetUserHomeDir():Promise<string>;

export function ListDir(arg1:string,arg2:types.AdditionalParams):Promise<Array<types.FileStruct>>;

export function OpenFileInSublimeText(arg1:string):Promise<void>;

export function OpenFileInVSCode(arg1:string):Promise<void>;

export function OpenImageInFeh(arg1:string):Promise<void>;

export function OpenPdfInXDG(arg1:string):Promise<void>;

export function OpenWithDefaultApplication(arg1:string,arg2:types.FileStruct):Promise<void>;

export function RemoveFile(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<types.FileStruct>>;
