// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFile(arg1, arg2) {
  return window['go']['backend']['App']['CopyFile'](arg1, arg2);
}

export function CreateDir(arg1) {
  return window['go']['backend']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['backend']['App']['CreateFile'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['backend']['App']['DeleteFile'](arg1);
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function FuzzyFindFiles(arg1, arg2) {
  return window['go']['backend']['App']['FuzzyFindFiles'](arg1, arg2);
}

export function GetUserHomeDir() {
  return window['go']['backend']['App']['GetUserHomeDir']();
}

export function ListDir(arg1, arg2) {
  return window['go']['backend']['App']['ListDir'](arg1, arg2);
}

export function OpenFileInSublimeText(arg1) {
  return window['go']['backend']['App']['OpenFileInSublimeText'](arg1);
}

export function OpenFileInVSCode(arg1) {
  return window['go']['backend']['App']['OpenFileInVSCode'](arg1);
}

export function OpenImageInFeh(arg1) {
  return window['go']['backend']['App']['OpenImageInFeh'](arg1);
}

export function OpenPdfInXDG(arg1) {
  return window['go']['backend']['App']['OpenPdfInXDG'](arg1);
}

export function OpenWithDefaultApplication(arg1, arg2) {
  return window['go']['backend']['App']['OpenWithDefaultApplication'](arg1, arg2);
}

export function RemoveFile(arg1) {
  return window['go']['backend']['App']['RemoveFile'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['backend']['App']['RenameFile'](arg1, arg2);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['backend']['App']['SearchFiles'](arg1, arg2);
}
